apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}wikivote
  labels:
    app.kubernetes.io/component: wikivote
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wikivote.deploy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: wikivote
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: wikivote
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Release.IsInstall }}
      serviceAccountName: {{ include "chart.resourceNamePrefix" . }}wikivote
      {{- end }}
      initContainers:
        - {{- include "chart.checkDbIsReadyInitContainer" . | nindent 10 }}
        {{- if .Release.IsInstall }}
        - name: check-dbmigrator-run
          image: "bitnami/kubectl:{{ template "chart.KubernetesVersion" . }}"
          imagePullPolicy: IfNotPresent
          command: ['kubectl', 'wait', '--namespace={{ .Release.Namespace }}', '--for=condition=complete', 'job/{{ include "chart.resourceNamePrefix" . }}dbmigrator-install', '--timeout=60s']
        {{- end }}
      containers:
        - name: wikivote
          image: {{ .Values.wikivote.deploy.image.repository }}:{{ .Values.imageTag | default (printf "v%s" .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          volumeMounts:
            - name: wikivote-config
              mountPath: {{ .Values.configDir | quote }}
              readOnly: true
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
            {{- toYaml .Values.wikivote.deploy.resources | nindent 12 }}
          command: ['wikivote', '-c', '{{ .Values.configDir }}/wikivote.yml']
      volumes:
        - name: wikivote-config
          secret:
            secretName: {{ include "chart.resourceNamePrefix" . }}wikivote-config
